"""empty message

Revision ID: c2bbe1661d87
Revises: 5b7b7086639b
Create Date: 2026-04-24 09:23:54.829333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bbe1661d87'
down_revision = '5b7b7086639b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('likinguser',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('likedpost',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('likedpost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('likinguser',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
